# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6b23df58ae86cec4eb2584ee67346b7d"
application_url = "https://joan-columns-factory-collaboration.trycloudflare.com"
embedded = true
name = "Bryt Designs Challenge"
handle = "bryt-designs-challenge"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_customers,read_metaobject_definitions,read_metaobjects,write_customers,write_metaobject_definitions,write_metaobjects,write_products,read_products"

[auth]
redirect_urls = [
  "https://joan-columns-factory-collaboration.trycloudflare.com/auth/callback",
  "https://joan-columns-factory-collaboration.trycloudflare.com/auth/shopify/callback",
  "https://joan-columns-factory-collaboration.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
